spring:
  datasource:
    url: jdbc:h2:mem:member_db;DB_CLOSE_DELAY=-1;mode=MySQL;TRACE_LEVEL_SYSTEM_OUT=2;
    username: test
    password: test
    hikari:
      driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:sql/tables.sql

eureka:
  client:
    enable: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:log/log4j2.xml


memberclub:
  infrastructure:
    config: local
    id: local
    lock: local
    feign:
      enabled: false
    retry: local