spring:
  datasource:
    ## url: jdbc:h2:tcp://localhost:9092/~/member_db;DB_CLOSE_DELAY=-1;mode=MySQL;
    url: jdbc:h2:mem:member_db;DB_CLOSE_DELAY=-1;mode=MySQL;
    ## #TRACE_LEVEL_SYSTEM_OUT=2;
    username: sa
    password: dean
    hikari:
      driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:sql/tables.sql
      mode: always
  h2:
    console:
      enabled: true
eureka:
  client:
    enable: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 禁用向 eureka 注册
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false


logging:
  config: classpath:log/log4j2-ut.xml

memberclub:
  infrastructure:
    config: none
    lock: none
    feign:
      enabled: false
    id: none

