server:
  port: 8081

spring:
  application:
    name: downstream-examples
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:log4j2.xml

